from pathlib import Path
from xml.sax.saxutils import escape
import re

ROOT = Path(__file__).resolve().parents[1]
ONTO = ROOT / "Airbnb.owx"
XI = "http://www.w3.org/2001/XMLSchema#int"
XD = "http://www.w3.org/2001/XMLSchema#decimal"
XF = "http://www.w3.org/2001/XMLSchema#double"
XB = "http://www.w3.org/2001/XMLSchema#boolean"

DATA = [
("EspacioTrabajo","Amenidad",[],[("categoriaAmenidad","TrabajoRemoto",None),("costoAdicional","0.0",XD),("disponibilidad","Permanente",None),("nombreAmenidad","EspacioTrabajo",None)]),
("Zona_LP_ACHUMANI","ZonaGeografica",[],[("ciudad","La Paz",None),("densidadUrbana","Media",None),("nombreZona","Achumani",None),("pais","Bolivia",None),("tipoZona","Urbana",None)]),
("Zona_CBBA_TIQUIPAYA","ZonaGeografica",[],[("ciudad","Cochabamba",None),("densidadUrbana","Baja",None),("nombreZona","Tiquipaya",None),("pais","Bolivia",None),("tipoZona","Rural",None)]),
("Zona_SCZ_URUBO","ZonaGeografica",[],[("ciudad","Santa Cruz de la Sierra",None),("densidadUrbana","Media",None),("nombreZona","Urubo",None),("pais","Bolivia",None),("tipoZona","Urbana",None)]),
("Zona_SUCRE_CENTRO","ZonaGeografica",[],[("ciudad","Sucre",None),("densidadUrbana","Alta",None),("nombreZona","Centro Historico",None),("pais","Bolivia",None),("tipoZona","Urbana",None)]),
("Zona_TARIJA_SANROQUE","ZonaGeografica",[],[("ciudad","Tarija",None),("densidadUrbana","Media",None),("nombreZona","San Roque",None),("pais","Bolivia",None),("tipoZona","Urbana",None)]),
("EstacionIrpavi","PuntoInteres",[],[("distanciaMetros","900",XI),("nombrePunto","Estacion Irpavi del Teleferico",None),("tipoPunto","Transporte",None)]),
("UnivalleTiquipaya","PuntoInteres",[],[("distanciaMetros","1200",XI),("nombrePunto","Campus Univalle Tiquipaya",None),("tipoPunto","Educacion",None)]),
("BiocentroGuembe","PuntoInteres",[],[("distanciaMetros","1700",XI),("nombrePunto","Biocentro Guembe",None),("tipoPunto","Ocio",None)]),
("Plaza25Mayo","PuntoInteres",[],[("distanciaMetros","450",XI),("nombrePunto","Plaza 25 de Mayo",None),("tipoPunto","Turismo",None)]),
("MercadoCampesinoTarija","PuntoInteres",[],[("distanciaMetros","700",XI),("nombrePunto","Mercado Campesino de Tarija",None),("tipoPunto","Comercio",None)]),
("GrupoEstudiantil","PerfilHuesped",[("tienePropositoViaje","ViajePasantia")],[("numeroAdultos","4",XI),("numeroMascotas","0",XI),("numeroNinos","0",XI),("presupuestoNoche","22.0",XD),("tipoViajero","GrupoEstudiantil",None)]),
("Ejecutivo","PerfilHuesped",[("tienePropositoViaje","ViajeProyecto")],[("numeroAdultos","1",XI),("numeroMascotas","0",XI),("numeroNinos","0",XI),("presupuestoNoche","85.0",XD),("tipoViajero","Negocios",None)]),
("FamiliaReubicacion","PerfilHuesped",[("tienePropositoViaje","ViajeReubicacion")],[("numeroAdultos","2",XI),("numeroMascotas","1",XI),("numeroNinos","2",XI),("presupuestoNoche","95.0",XD),("tipoViajero","Familia",None)]),
("ParejaEscapada","PerfilHuesped",[("tienePropositoViaje","ViajeEscapada")],[("numeroAdultos","2",XI),("numeroMascotas","0",XI),("numeroNinos","0",XI),("presupuestoNoche","70.0",XD),("tipoViajero","Pareja",None)]),
("AmigosCongreso","PerfilHuesped",[("tienePropositoViaje","ViajeCongreso")],[("numeroAdultos","4",XI),("numeroMascotas","0",XI),("numeroNinos","0",XI),("presupuestoNoche","80.0",XD),("tipoViajero","GrupoAmigos",None)]),
("PoliticaCorporativa","Politica",[],[("disponibleInmediatamente","false",XB),("edadMinimaHuesped","21",XI),("maximoNoches","45",XI),("minimoNoches","2",XI),("reglaCigarrillos","Prohibido",None),("reglaMascotas","Prohibido",None),("tipoCancelacion","Moderada",None)]),
("PoliticaResidencial","Politica",[],[("disponibleInmediatamente","true",XB),("edadMinimaHuesped","18",XI),("maximoNoches","180",XI),("minimoNoches","7",XI),("reglaCigarrillos","SoloExterior",None),("reglaMascotas","Permitido",None),("tipoCancelacion","Flexible",None)]),
("PoliticaEventos","Politica",[],[("disponibleInmediatamente","false",XB),("edadMinimaHuesped","25",XI),("maximoNoches","5",XI),("minimoNoches","1",XI),("reglaCigarrillos","Prohibido",None),("reglaMascotas","Prohibido",None),("tipoCancelacion","Estricta",None)]),
("PoliticaEstudiantil","Politica",[],[("disponibleInmediatamente","true",XB),("edadMinimaHuesped","18",XI),("maximoNoches","120",XI),("minimoNoches","15",XI),("reglaCigarrillos","Prohibido",None),("reglaMascotas","Prohibido",None),("tipoCancelacion","Moderada",None)]),
("PoliticaEscapada","Politica",[],[("disponibleInmediatamente","true",XB),("edadMinimaHuesped","18",XI),("maximoNoches","14",XI),("minimoNoches","1",XI),("reglaCigarrillos","SoloExterior",None),("reglaMascotas","Permitido",None),("tipoCancelacion","Flexible",None)]),
("ViajeReubicacion","PropositoViaje",[],[("duracionEstadia","30",XI),("modalidadTrabajo","Hibrido",None),("tipoPropositoViaje","Reubicacion",None)]),
("ViajeCongreso","PropositoViaje",[],[("duracionEstadia","4",XI),("modalidadTrabajo","Presencial",None),("tipoPropositoViaje","EventoEspecial",None)]),
("ViajePasantia","PropositoViaje",[],[("duracionEstadia","60",XI),("modalidadTrabajo","Presencial",None),("tipoPropositoViaje","Estudios",None)]),
("ViajeProyecto","PropositoViaje",[],[("duracionEstadia","14",XI),("modalidadTrabajo","Hibrido",None),("tipoPropositoViaje","Profesional",None)]),
("ViajeEscapada","PropositoViaje",[],[("duracionEstadia","5",XI),("modalidadTrabajo","NoAplica",None),("tipoPropositoViaje","Vacacional",None)]),
("Apto_Achumani_1","Apartamento",[("compatibleCon","Ejecutivo"),("tieneAmenidad","Wifi"),("tieneAmenidad","Cocina"),("tieneAmenidad","EspacioTrabajo"),("tienePolitica","PoliticaCorporativa"),("ubicadaEn","Zona_LP_ACHUMANI")],[("areaTotal","78.0",XF),("calificacionPromedio","4.7",XD),("capacidadMaxima","3",XI),("descripcionPropiedad","Departamento de dos ambientes en Achumani, util para trabajo remoto y estadias ejecutivas.",None),("nombrePropiedad","Departamento con vista en Achumani",None),("numeroBanos","1",XI),("numeroDormitorios","1",XI),("numeroPiso","5",XI),("precioNoche","52.0",XD),("seguridadEdificio","Intercomunicador",None),("tieneAscensor","true",XB),("tipoAcceso","LlaveElectronica",None),("tipoEspacioExterior","Balcon",None),("tipoEstacionamiento","GarajePrivado",None)]),
("Apto_Tiquipaya_1","Apartamento",[("compatibleCon","FamiliaReubicacion"),("tieneAmenidad","Wifi"),("tieneAmenidad","Cocina"),("tieneAmenidad","ParkingGratis"),("tienePolitica","PoliticaResidencial"),("ubicadaEn","Zona_CBBA_TIQUIPAYA")],[("areaTotal","82.0",XF),("calificacionPromedio","4.8",XD),("capacidadMaxima","4",XI),("descripcionPropiedad","Departamento familiar en Tiquipaya con cocina equipada y parqueo gratuito.",None),("nombrePropiedad","Departamento familiar en Tiquipaya",None),("numeroBanos","2",XI),("numeroDormitorios","2",XI),("numeroPiso","2",XI),("precioNoche","58.0",XD),("seguridadEdificio","SoloLlave",None),("tieneAscensor","false",XB),("tipoAcceso","LlaveElectronica",None),("tipoEspacioExterior","Terraza",None),("tipoEstacionamiento","GarajePrivado",None)]),
("Apto_Urubo_1","Apartamento",[("compatibleCon","ParejaEscapada"),("tieneAmenidad","Piscina"),("tieneAmenidad","Wifi"),("tieneAmenidad","Desayuno"),("tienePolitica","PoliticaEscapada"),("ubicadaEn","Zona_SCZ_URUBO")],[("areaTotal","70.0",XF),("calificacionPromedio","4.9",XD),("capacidadMaxima","2",XI),("descripcionPropiedad","Loft luminoso en Urubo con piscina del condominio, pensado para escapadas cortas.",None),("nombrePropiedad","Loft con piscina en Urubo",None),("numeroBanos","1",XI),("numeroDormitorios","1",XI),("numeroPiso","3",XI),("precioNoche","95.0",XD),("seguridadEdificio","Vigilancia24h",None),("tieneAscensor","true",XB),("tipoAcceso","LlaveElectronica",None),("tipoEspacioExterior","Terraza",None),("tipoEstacionamiento","GarajePrivado",None)]),
("Apto_CentroSucre_1","Apartamento",[("compatibleCon","GrupoEstudiantil"),("tieneAmenidad","Wifi"),("tieneAmenidad","Cocina"),("tienePolitica","PoliticaEstudiantil"),("ubicadaEn","Zona_SUCRE_CENTRO")],[("areaTotal","60.0",XF),("calificacionPromedio","4.6",XD),("capacidadMaxima","2",XI),("descripcionPropiedad","Apartamento compacto en el centro historico de Sucre, adecuado para estudiantes o pasantes.",None),("nombrePropiedad","Apartamento estudiantil en centro de Sucre",None),("numeroBanos","1",XI),("numeroDormitorios","1",XI),("numeroPiso","2",XI),("precioNoche","40.0",XD),("seguridadEdificio","Intercomunicador",None),("tieneAscensor","false",XB),("tipoAcceso","LlaveElectronica",None),("tipoEspacioExterior","Balcon",None),("tipoEstacionamiento","NoDisponible",None)]),
("Apto_SanRoque_1","Apartamento",[("compatibleCon","AmigosCongreso"),("tieneAmenidad","AireAcondicionado"),("tieneAmenidad","Parking"),("tienePolitica","PoliticaCorporativa"),("ubicadaEn","Zona_TARIJA_SANROQUE")],[("areaTotal","76.0",XF),("calificacionPromedio","4.5",XD),("capacidadMaxima","3",XI),("descripcionPropiedad","Departamento funcional en San Roque para grupos pequenos que asisten a ferias o congresos.",None),("nombrePropiedad","Departamento funcional en San Roque",None),("numeroBanos","1",XI),("numeroDormitorios","2",XI),("numeroPiso","4",XI),("precioNoche","47.0",XD),("seguridadEdificio","Intercomunicador",None),("tieneAscensor","true",XB),("tipoAcceso","LlaveElectronica",None),("tipoEspacioExterior","Balcon",None),("tipoEstacionamiento","Calle",None)]),
("Casa_Achumani_1","Casa",[("compatibleCon","FamiliaReubicacion"),("tieneAmenidad","Cocina"),("tieneAmenidad","Wifi"),("tieneAmenidad","ParkingGratis"),("tienePolitica","PoliticaResidencial"),("ubicadaEn","Zona_LP_ACHUMANI")],[("areaTotal","160.0",XF),("calificacionPromedio","4.8",XD),("capacidadMaxima","6",XI),("descripcionPropiedad","Casa amplia con jardin en Achumani, pensada para familias que necesitan una base comoda por varias semanas.",None),("nombrePropiedad","Casa amplia con jardin en Achumani",None),("numeroBanos","3",XI),("numeroDormitorios","4",XI),("numeroPlantas","2",XI),("precioNoche","85.0",XD),("tieneJardin","true",XB),("tipoAcceso","LlaveTradicional",None),("tipoEspacioExterior","Jardin",None),("tipoEstacionamiento","GarajePrivado",None)]),
("Casa_Tiquipaya_1","Casa",[("compatibleCon","Familiar"),("tieneAmenidad","Piscina"),("tieneAmenidad","Cocina"),("tieneAmenidad","Lavanderia"),("tienePolitica","PoliticaPetFriendly"),("ubicadaEn","Zona_CBBA_TIQUIPAYA")],[("areaTotal","180.0",XF),("calificacionPromedio","4.7",XD),("capacidadMaxima","7",XI),("descripcionPropiedad","Casa de descanso en Tiquipaya con piscina y patio amplio, apropiada para vacaciones familiares.",None),("nombrePropiedad","Casa de descanso en Tiquipaya",None),("numeroBanos","3",XI),("numeroDormitorios","4",XI),("numeroPlantas","1",XI),("precioNoche","90.0",XD),("tieneJardin","true",XB),("tipoAcceso","LlaveTradicional",None),("tipoEspacioExterior","Jardin",None),("tipoEstacionamiento","GarajePrivado",None)]),
("Casa_Urubo_1","Casa",[("compatibleCon","ParejaEscapada"),("tieneAmenidad","Piscina"),("tieneAmenidad","Wifi"),("tieneAmenidad","AireAcondicionado"),("tienePolitica","PoliticaEscapada"),("ubicadaEn","Zona_SCZ_URUBO")],[("areaTotal","175.0",XF),("calificacionPromedio","4.9",XD),("capacidadMaxima","6",XI),("descripcionPropiedad","Casa moderna en Urubo con piscina y terraza, pensada para escapadas comodas con privacidad.",None),("nombrePropiedad","Casa moderna en Urubo",None),("numeroBanos","3",XI),("numeroDormitorios","3",XI),("numeroPlantas","2",XI),("precioNoche","120.0",XD),("tieneJardin","true",XB),("tipoAcceso","LlaveElectronica",None),("tipoEspacioExterior","Jardin",None),("tipoEstacionamiento","GarajePrivado",None)]),
("Casa_CentroSucre_1","Casa",[("compatibleCon","AmigosCongreso"),("tieneAmenidad","Cocina"),("tieneAmenidad","Wifi"),("tieneAmenidad","Limpieza"),("tienePolitica","PoliticaModerada"),("ubicadaEn","Zona_SUCRE_CENTRO")],[("areaTotal","140.0",XF),("calificacionPromedio","4.6",XD),("capacidadMaxima","5",XI),("descripcionPropiedad","Casona patrimonial del centro de Sucre, util para grupos que quieren caminar por el casco historico.",None),("nombrePropiedad","Casona patrimonial en centro de Sucre",None),("numeroBanos","2",XI),("numeroDormitorios","3",XI),("numeroPlantas","2",XI),("precioNoche","68.0",XD),("tieneJardin","false",XB),("tipoAcceso","LlaveTradicional",None),("tipoEspacioExterior","Patio",None),("tipoEstacionamiento","NoDisponible",None)]),
("Casa_SanRoque_1","Casa",[("compatibleCon","ParejaEscapada"),("tieneAmenidad","Cocina"),("tieneAmenidad","Wifi"),("tieneAmenidad","AireAcondicionado"),("tienePolitica","PoliticaEscapada"),("ubicadaEn","Zona_TARIJA_SANROQUE")],[("areaTotal","130.0",XF),("calificacionPromedio","4.4",XD),("capacidadMaxima","5",XI),("descripcionPropiedad","Casa tarijena con galeria en San Roque, comoda para estadias cortas con ambiente residencial.",None),("nombrePropiedad","Casa tarijena con galeria en San Roque",None),("numeroBanos","2",XI),("numeroDormitorios","3",XI),("numeroPlantas","1",XI),("precioNoche","62.0",XD),("tieneJardin","true",XB),("tipoAcceso","LlaveTradicional",None),("tipoEspacioExterior","Jardin",None),("tipoEstacionamiento","GarajePrivado",None)]),
("Hab_Compartida_Achumani_1","HabitacionCompartida",[("compatibleCon","GrupoEstudiantil"),("tieneAmenidad","Wifi"),("tieneAmenidad","EspacioTrabajo"),("tienePolitica","PoliticaEstudiantil"),("ubicadaEn","Zona_LP_ACHUMANI")],[("calificacionPromedio","4.3",XD),("capacidadDormitorio","4",XI),("capacidadMaxima","1",XI),("descripcionPropiedad","Cama en residencia compartida de Achumani, orientada a estudiantes con espacios de estudio.",None),("dimensionesHabitacion","24.0",XF),("nombrePropiedad","Cama en residencia de Achumani",None),("numeroBanos","0",XI),("numeroBanosCompartidos","2",XI),("numeroDormitorios","1",XI),("numeroHabitacion","A-201",None),("precioNoche","14.0",XD),("tipoAcceso","CodigoNumerico",None),("tipoBano","Compartido",None)]),
("Hab_Compartida_Tiquipaya_1","HabitacionCompartida",[("compatibleCon","GrupoEstudiantil"),("tieneAmenidad","Wifi"),("tieneAmenidad","Cocina"),("tienePolitica","PoliticaEstudiantil"),("ubicadaEn","Zona_CBBA_TIQUIPAYA")],[("calificacionPromedio","4.5",XD),("capacidadDormitorio","6",XI),("capacidadMaxima","1",XI),("descripcionPropiedad","Cama en casa compartida de Tiquipaya, adecuada para estudiantes con presupuesto moderado.",None),("dimensionesHabitacion","28.0",XF),("nombrePropiedad","Cama en casa compartida de Tiquipaya",None),("numeroBanos","0",XI),("numeroBanosCompartidos","2",XI),("numeroDormitorios","1",XI),("numeroHabitacion","TQ-5",None),("precioNoche","11.0",XD),("tipoAcceso","CodigoNumerico",None),("tipoBano","Compartido",None)]),
("Hab_Compartida_Urubo_1","HabitacionCompartida",[("compatibleCon","AmigosCongreso"),("tieneAmenidad","Wifi"),("tieneAmenidad","AireAcondicionado"),("tienePolitica","PoliticaCorporativa"),("ubicadaEn","Zona_SCZ_URUBO")],[("calificacionPromedio","4.2",XD),("capacidadDormitorio","4",XI),("capacidadMaxima","1",XI),("descripcionPropiedad","Cama en residencia compartida de Urubo, pensada para asistentes a ferias o eventos breves.",None),("dimensionesHabitacion","22.0",XF),("nombrePropiedad","Cama en residencia de Urubo",None),("numeroBanos","0",XI),("numeroBanosCompartidos","2",XI),("numeroDormitorios","1",XI),("numeroHabitacion","U-04",None),("precioNoche","18.0",XD),("tipoAcceso","CodigoNumerico",None),("tipoBano","Compartido",None)]),
("Hab_Compartida_CentroSucre_1","HabitacionCompartida",[("compatibleCon","GrupoEstudiantil"),("tieneAmenidad","Wifi"),("tieneAmenidad","Cocina"),("tienePolitica","PoliticaEstudiantil"),("ubicadaEn","Zona_SUCRE_CENTRO")],[("calificacionPromedio","4.6",XD),("capacidadDormitorio","5",XI),("capacidadMaxima","1",XI),("descripcionPropiedad","Cama en hostal del centro de Sucre, util para pasantes o viajeros jovenes.",None),("dimensionesHabitacion","20.0",XF),("nombrePropiedad","Cama en hostal del centro de Sucre",None),("numeroBanos","0",XI),("numeroBanosCompartidos","2",XI),("numeroDormitorios","1",XI),("numeroHabitacion","SC-2",None),("precioNoche","12.0",XD),("tipoAcceso","CodigoNumerico",None),("tipoBano","Compartido",None)]),
("Hab_Compartida_SanRoque_1","HabitacionCompartida",[("compatibleCon","Individual"),("tieneAmenidad","Wifi"),("tieneAmenidad","Parking"),("tienePolitica","PoliticaModerada"),("ubicadaEn","Zona_TARIJA_SANROQUE")],[("calificacionPromedio","4.1",XD),("capacidadDormitorio","4",XI),("capacidadMaxima","1",XI),("descripcionPropiedad","Cama en residencial de San Roque, sencilla y funcional para viajeros individuales.",None),("dimensionesHabitacion","19.0",XF),("nombrePropiedad","Cama en residencial de San Roque",None),("numeroBanos","0",XI),("numeroBanosCompartidos","2",XI),("numeroDormitorios","1",XI),("numeroHabitacion","SR-6",None),("precioNoche","13.0",XD),("tipoAcceso","CodigoNumerico",None),("tipoBano","Compartido",None)]),
("Hab_Privada_Achumani_1","HabitacionPrivada",[("compatibleCon","Ejecutivo"),("tieneAmenidad","Wifi"),("tieneAmenidad","EspacioTrabajo"),("tienePolitica","PoliticaCorporativa"),("ubicadaEn","Zona_LP_ACHUMANI")],[("calificacionPromedio","4.7",XD),("capacidadMaxima","2",XI),("descripcionPropiedad","Habitacion privada en Achumani, comoda para trabajo remoto y descanso en una zona residencial.",None),("dimensionesHabitacion","18.0",XF),("nombrePropiedad","Habitacion privada en Achumani",None),("numeroBanos","1",XI),("numeroDormitorios","1",XI),("numeroHabitacion","A-12",None),("precioNoche","32.0",XD),("tipoAcceso","LlaveTradicional",None),("tipoBano","EnSuite",None),("tipoCama","Queen",None)]),
("Hab_Privada_Tiquipaya_1","HabitacionPrivada",[("compatibleCon","ParejaEscapada"),("tieneAmenidad","Wifi"),("tieneAmenidad","Desayuno"),("tienePolitica","PoliticaEscapada"),("ubicadaEn","Zona_CBBA_TIQUIPAYA")],[("calificacionPromedio","4.8",XD),("capacidadMaxima","2",XI),("descripcionPropiedad","Habitacion privada con jardin en Tiquipaya, agradable para escapadas tranquilas en pareja.",None),("dimensionesHabitacion","20.0",XF),("nombrePropiedad","Habitacion privada con jardin en Tiquipaya",None),("numeroBanos","1",XI),("numeroDormitorios","1",XI),("numeroHabitacion","TQ-2",None),("precioNoche","28.0",XD),("tipoAcceso","LlaveTradicional",None),("tipoBano","EnSuite",None),("tipoCama","Doble",None)]),
("Hab_Privada_Urubo_1","HabitacionPrivada",[("compatibleCon","ParejaEscapada"),("tieneAmenidad","Wifi"),("tieneAmenidad","AireAcondicionado"),("tieneAmenidad","Piscina"),("tienePolitica","PoliticaEscapada"),("ubicadaEn","Zona_SCZ_URUBO")],[("calificacionPromedio","4.9",XD),("capacidadMaxima","2",XI),("descripcionPropiedad","Suite privada en Urubo con acceso a piscina, enfocada en comodidad para escapadas cortas.",None),("dimensionesHabitacion","22.0",XF),("nombrePropiedad","Suite privada en Urubo",None),("numeroBanos","1",XI),("numeroDormitorios","1",XI),("numeroHabitacion","U-11",None),("precioNoche","45.0",XD),("tipoAcceso","LlaveTradicional",None),("tipoBano","EnSuite",None),("tipoCama","Queen",None)]),
("Hab_Privada_CentroSucre_1","HabitacionPrivada",[("compatibleCon","GrupoEstudiantil"),("tieneAmenidad","Wifi"),("tieneAmenidad","Cocina"),("tienePolitica","PoliticaEstudiantil"),("ubicadaEn","Zona_SUCRE_CENTRO")],[("calificacionPromedio","4.5",XD),("capacidadMaxima","1",XI),("descripcionPropiedad","Habitacion privada economica en centro de Sucre, pensada para estudiantes o pasantes.",None),("dimensionesHabitacion","14.0",XF),("nombrePropiedad","Habitacion privada para estudiante en Sucre",None),("numeroBanos","1",XI),("numeroDormitorios","1",XI),("numeroHabitacion","SC-8",None),("precioNoche","20.0",XD),("tipoAcceso","LlaveTradicional",None),("tipoBano","EnSuite",None),("tipoCama","Individual",None)]),
("Hab_Privada_SanRoque_1","HabitacionPrivada",[("compatibleCon","ParejaEscapada"),("tieneAmenidad","Wifi"),("tieneAmenidad","Parking"),("tienePolitica","PoliticaFlexible"),("ubicadaEn","Zona_TARIJA_SANROQUE")],[("calificacionPromedio","4.4",XD),("capacidadMaxima","2",XI),("descripcionPropiedad","Habitacion privada en San Roque, comoda para parejas que buscan moverse facilmente por Tarija.",None),("dimensionesHabitacion","17.0",XF),("nombrePropiedad","Habitacion privada en San Roque",None),("numeroBanos","1",XI),("numeroDormitorios","1",XI),("numeroHabitacion","SR-3",None),("precioNoche","26.0",XD),("tipoAcceso","LlaveTradicional",None),("tipoBano","EnSuite",None),("tipoCama","Doble",None)]),
("Villa_Achumani_1","Villa",[("compatibleCon","Ejecutivo"),("tieneAmenidad","Wifi"),("tieneAmenidad","Cocina"),("tieneAmenidad","ParkingGratis"),("tienePolitica","PoliticaCorporativa"),("ubicadaEn","Zona_LP_ACHUMANI")],[("areaTotal","380.0",XF),("calificacionPromedio","4.8",XD),("capacidadEventos","30",XI),("capacidadMaxima","10",XI),("descripcionPropiedad","Residencia amplia con vistas en Achumani, apta para retiros corporativos pequenos y reuniones privadas.",None),("nombrePropiedad","Residencia con vistas en Achumani",None),("numeroBanos","4",XI),("numeroDormitorios","4",XI),("precioNoche","260.0",XD),("tipoAcceso","CodigoNumerico",None),("tipoEspacioExterior","Terraza",None),("tipoEstacionamiento","GarajeMultiple",None)]),
("Villa_Tiquipaya_1","Villa",[("compatibleCon","Familiar"),("tieneAmenidad","Piscina"),("tieneAmenidad","Cocina"),("tieneAmenidad","ParkingGratis"),("tieneAmenidad","Lavanderia"),("tienePolitica","PoliticaPetFriendly"),("ubicadaEn","Zona_CBBA_TIQUIPAYA")],[("areaTotal","520.0",XF),("calificacionPromedio","4.9",XD),("capacidadEventos","60",XI),("capacidadMaxima","16",XI),("descripcionPropiedad","Quinta amplia en Tiquipaya con jardin y piscina, adecuada para reuniones familiares grandes.",None),("nombrePropiedad","Quinta con jardin en Tiquipaya",None),("numeroBanos","5",XI),("numeroDormitorios","6",XI),("precioNoche","320.0",XD),("tipoAcceso","CodigoNumerico",None),("tipoEspacioExterior","Jardin",None),("tipoEstacionamiento","GarajeMultiple",None)]),
("Villa_Urubo_1","Villa",[("compatibleCon","AmigosCongreso"),("tieneAmenidad","Piscina"),("tieneAmenidad","Wifi"),("tieneAmenidad","AireAcondicionado"),("tienePolitica","PoliticaEventos"),("ubicadaEn","Zona_SCZ_URUBO")],[("areaTotal","480.0",XF),("calificacionPromedio","5.0",XD),("capacidadEventos","70",XI),("capacidadMaxima","18",XI),("descripcionPropiedad","Villa premium en Urubo, ideal para grupos que buscan privacidad y una piscina amplia.",None),("nombrePropiedad","Villa premium en Urubo",None),("numeroBanos","5",XI),("numeroDormitorios","6",XI),("precioNoche","420.0",XD),("tipoAcceso","CodigoNumerico",None),("tipoEspacioExterior","Patio",None),("tipoEstacionamiento","GarajeMultiple",None)]),
("Villa_CentroSucre_1","Villa",[("compatibleCon","AmigosCongreso"),("tieneAmenidad","Cocina"),("tieneAmenidad","Wifi"),("tieneAmenidad","ParkingGratis"),("tienePolitica","PoliticaEventos"),("ubicadaEn","Zona_SUCRE_CENTRO")],[("areaTotal","360.0",XF),("calificacionPromedio","4.7",XD),("capacidadEventos","25",XI),("capacidadMaxima","9",XI),("descripcionPropiedad","Casona privada para eventos pequenos en Sucre, con patio interior y varios dormitorios.",None),("nombrePropiedad","Casona privada para eventos en Sucre",None),("numeroBanos","4",XI),("numeroDormitorios","5",XI),("precioNoche","240.0",XD),("tipoAcceso","CodigoNumerico",None),("tipoEspacioExterior","Patio",None),("tipoEstacionamiento","GarajePrivado",None)]),
("Villa_SanRoque_1","Villa",[("compatibleCon","FamiliaReubicacion"),("tieneAmenidad","Piscina"),("tieneAmenidad","Wifi"),("tieneAmenidad","ParkingGratis"),("tienePolitica","PoliticaResidencial"),("ubicadaEn","Zona_TARIJA_SANROQUE")],[("areaTotal","430.0",XF),("calificacionPromedio","4.8",XD),("capacidadEventos","40",XI),("capacidadMaxima","14",XI),("descripcionPropiedad","Casaquinta en San Roque con piscina y parqueo multiple, adecuada para familias grandes o eventos privados.",None),("nombrePropiedad","Casaquinta en San Roque",None),("numeroBanos","5",XI),("numeroDormitorios","6",XI),("precioNoche","290.0",XD),("tipoAcceso","CodigoNumerico",None),("tipoEspacioExterior","Jardin",None),("tipoEstacionamiento","GarajeMultiple",None)]),
]

ZONE_LINKS = [("Zona_LP_ACHUMANI","EstacionIrpavi"),("Zona_CBBA_TIQUIPAYA","UnivalleTiquipaya"),("Zona_SCZ_URUBO","BiocentroGuembe"),("Zona_SUCRE_CENTRO","Plaza25Mayo"),("Zona_TARIJA_SANROQUE","MercadoCampesinoTarija")]

def lit(v, dt): return f'<Literal datatypeIRI="{dt}">{escape(v)}</Literal>' if dt else f"<Literal>{escape(v)}</Literal>"
def decl(i): return f'    <Declaration>\n        <NamedIndividual IRI="#{i}"/>\n    </Declaration>\n'
def ca(c,i): return f'    <ClassAssertion>\n        <Class IRI="#{c}"/>\n        <NamedIndividual IRI="#{i}"/>\n    </ClassAssertion>\n'
def oa(p,s,o): return f'    <ObjectPropertyAssertion>\n        <ObjectProperty IRI="#{p}"/>\n        <NamedIndividual IRI="#{s}"/>\n        <NamedIndividual IRI="#{o}"/>\n    </ObjectPropertyAssertion>\n'
def da(p,s,v,dt): return f'    <DataPropertyAssertion>\n        <DataProperty IRI="#{p}"/>\n        <NamedIndividual IRI="#{s}"/>\n        {lit(v,dt)}\n    </DataPropertyAssertion>\n'

text = ONTO.read_text(encoding="utf-8")
decls = set(re.findall(r'<Declaration>\s*<NamedIndividual IRI="#([^"]+)"/>\s*</Declaration>', text, re.S))
cas = set(re.findall(r'<ClassAssertion>\s*<Class IRI="#([^"]+)"/>\s*<NamedIndividual IRI="#([^"]+)"/>\s*</ClassAssertion>', text, re.S))
oas = set(re.findall(r'<ObjectPropertyAssertion>\s*<ObjectProperty IRI="#([^"]+)"/>\s*<NamedIndividual IRI="#([^"]+)"/>\s*<NamedIndividual IRI="#([^"]+)"/>\s*</ObjectPropertyAssertion>', text, re.S))
das = set(re.findall(r'<DataPropertyAssertion>\s*<DataProperty IRI="#([^"]+)"/>\s*<NamedIndividual IRI="#([^"]+)"/>\s*<Literal(?: datatypeIRI="([^"]+)")?>(.*?)</Literal>\s*</DataPropertyAssertion>', text, re.S))

new_decl, new_ax = [], []
for i, c, objs, datas in DATA:
    if i not in decls: new_decl.append(decl(i))
    if (c, i) not in cas: new_ax.append(ca(c, i))
    for p, o in objs:
        if (p, i, o) not in oas: new_ax.append(oa(p, i, o))
    for p, v, dt in datas:
        if (p, i, dt or "", v) not in das: new_ax.append(da(p, i, v, dt))
for z, p in ZONE_LINKS:
    if ("tienePuntoInteres", z, p) not in oas: new_ax.append(oa("tienePuntoInteres", z, p))

if new_decl: text = text.replace("    <SubClassOf>", "".join(new_decl) + "    <SubClassOf>", 1)
if new_ax: text = text.replace("    <ObjectPropertyDomain>", "".join(new_ax) + "    <ObjectPropertyDomain>", 1)
ONTO.write_text(text, encoding="utf-8")
